- name: Create the directory
  win_file:
    path: {{ share_directory }}
    state: directory

- name: Make share
  win_command: "net share space_rocks={{ share_directory }} /GRANT:Everyone,FULL"

- name: copy files to created share
  win_copy: 
    src: files/
    dest:"{{ share_directory }}"
