---
# tasks file for accounts-predeploy


- name: Include user list
  include_vars: "local_accounts.yml"
  tags: linux_accounts

- name: Add user accounts - Linux
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
  with_items: "{{ accounts }}"
  when: ansible_system == "Linux"
  tags: linux_accounts

- name: Add user accounts - Windows
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
  with_items: "{{ accounts }}"
  when: ansible_system == "Windows"

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
    groups: 
      - "sudo"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "Debian"
  tags: linux_accounts

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
    groups: 
      - "wheel"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "RedHat"
  tags: linux_accounts

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
    groups: 
      - "sudoers"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "BSD"

- name: Add local admin accounts
  win_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups: 
      - "Administrators"
  with_items: "{{ admin_accounts }}"
  when: ansible_system == "Windows"
