- name: Add SSSD support to nsswitch.conf
  template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf
            owner=root group=root mode=0600
  notify: restart sssd

- name: Install PAM homedir creation
  package:
    name: pam_mkhomedir
    state: present

- name: Make copy of pam.d/system file
  copy:
    src: /etc/pam.d/system
    dest: /etc/pam.d/system.dist
    owner: root
    group: root
    mode: 0600

- name: Add pam sshd config
  template: src=pamsshd.conf.j2 dest=/etc/pam.d/sshd
            owner=root group=root mode=0600

- name: Add pam system config
  template: src=pamsystem.conf.j2 dest=/etc/pam.d/system
            owner=root group=root mode=0600

- name: Add pam sshd config
  template: src=pamsu.conf.j2 dest=/etc/pam.d/su
            owner=root group=root mode=0600

- name: Remove openldap client
  pkgng:
    name: openldap-client
    state: absent

- name: Install SASL enabled OpenLDAP client
  pkgng:
    name: openldap-sasl-client
    state: present
