---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - pip install -r requirements.txt
  - pip install ansible-lint

script:
  - ansible-playbook -i hosts predeploy.yml --syntax-check
  - ansible-playbook -i hosts deploy.yml --syntax-check
  - ansible-lint predeploy.yml
  - ansible-lint deploy.yml
