---
- hosts: Linux
  roles:
    - packages

- hosts: FreeBSD
  roles:
    - jenkinsbsd-predeploy

- hosts: all
  roles:
    - accounts-predeploy

- hosts: Ubuntu
  roles:
    - ecommerce-predeploy

- hosts: FreeBSD
  roles:
    - jenkinsbsd-predeploy

- hosts: WindowsMail
  roles:
    - mail-predeploy


