---
- include_tasks: install.yml
  notify: Configure Jenkins

- name: Configure Jenkins
  include_tasks: configure.yml

- include_tasks: startup.yml
- pause:
   seconds: 10
- include_tasks: plugins.yml
- include_tasks: jobs.yml
