---
# tasks file for accounts-predeploy


- name: Include user list
  include_vars: "local_accounts.yml"
  tags: linux_accounts

- name: Add user accounts - Linux
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
  with_items: "{{ accounts }}"

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password_hash }}"
    state: present
    groups: 
      - "sudo"
  with_items: "{{ admin_accounts }}"
