---
- name: Apply the ifcfg template
  template:
    src: templates/ifcfg
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
  notify:
    - Restart network

- name: Apply the resolv.conf template
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf

- name: Apply the hosts template
  template:
    src: templates/hosts
    dest: /etc/hosts
  notify:
    - Restart networking
