---

- name: Include OS specific package names
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Update apt cache when package manager is apt
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: Install headers Debian
  shell: "apt-get -y install linux-headers-$(uname -r)"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install headers Centos7
  shell: "yum install -y kernel-devel-$(uname -r)"
  when: (ansible_distribution == 'CentOS')
