# Notes:
#  In order to promote a host to a domain controller, it must have a local administrator password set that meets
#  password complexity requirements (typically, 8 chars, 1 lowercase, 1 uppercase, 1 num/special char)
#  cmd: net user administrator *
---
- name: Copy join domain script over
  win_copy:
    src: files/Join-Domain.ps1
    dest: C:\Users\Administrator\Join-Domain.ps1

- name: Run join domain script
  win_shell: C:\Users\Administrator\Join-Domain.ps1 "{{ domainname }}" "{{ username }}" "{{ password }}"
